### ISSUE TITLE
No sound coming out of HomePod

### ISSUE THREAD

**Issue by scout1256** [AlexanderBabel/owntone#10]
**Describe the bug**
[  LOG]     mdns: Avahi state change: Client collision

followed this guide: https://github.com/librespot-org/librespot-java/tree/dev/player#audio-output-configuration
Could not find "Available mixers: ..." or "mixer" in log.

**To Reproduce**
-

**Expected behavior**
Sound played on Homepod mini

**Screenshots/Stracktraces/Logs**
```
Withdrawing address record for fe80::88ad:89ff:fef8:36f1 on vethea43337.
Withdrawing address record for fe80::b83a:26ff:feef:465a on veth51c31fb.
Withdrawing address record for fe80::e89b:eff:fe16:9518 on veth0a68914.
Withdrawing address record for fe80::2cc1:b8ff:fed1:aa1e on veth76848d9.
Withdrawing address record for fe80::b0e2:b7ff:fe09:e602 on vethd7bbce6.
Withdrawing address record for fe80::60b6:58ff:fecc:7ffa on veth8e6ba93.
Withdrawing address record for fe80::ac49:9dff:fed6:fcfc on vethd2dd562.
Withdrawing address record for fe80::42:34ff:fe64:4f9e on hassio.
Withdrawing address record for fe80::42:53ff:fef6:ad9b on docker0.
Withdrawing address record for 172.17.0.1 on docker0.
Withdrawing address record for fd23:b292:d298:4011:6ccc:c48c:cab:6f51 on enp6s18.
Withdrawing address record for 192.168.1.70 on enp6s18.
Withdrawing address record for ::1 on lo.
Withdrawing address record for 127.0.0.1 on lo.
Host name conflict, retrying with 63120367-homepod-connect-35
Registering new address record for fe80::b4c1:f9ff:fe6f:fa82 on veth030d762.*.
Registering new address record for fe80::b46d:40ff:fe74:4ef4 on veth6c757f5.*.
Registering new address record for fe80::f839:81ff:feea:3d3e on vethcedecb9.*.
Registering new address record for fe80::f052:32ff:fe50:623d on veth000fdb3.*.
Registering new address record for fe80::c4b1:e5ff:fe4c:883f on veth5c9ac3b.*.
Registering new address record for fe80::481:4ff:fe7b:98d1 on vethb49d1d5.*.
Registering new address record for fe80::bca1:feff:fea8:3abf on veth3a40eae.*.
Registering new address record for fe80::88ad:89ff:fef8:36f1 on vethea43337.*.
Registering new address record for fe80::b83a:26ff:feef:465a on veth51c31fb.*.
Registering new address record for fe80::e89b:eff:fe16:9518 on veth0a68914.*.
Registering new address record for fe80::2cc1:b8ff:fed1:aa1e on veth76848d9.*.
Registering new address record for fe80::b0e2:b7ff:fe09:e602 on vethd7bbce6.*.
Registering new address record for fe80::60b6:58ff:fecc:7ffa on veth8e6ba93.*.
Registering new address record for fe80::ac49:9dff:fed6:fcfc on vethd2dd562.*.
Registering new address record for fe80::42:34ff:fe64:4f9e on hassio.*.
Registering new address record for 172.30.32.1 on hassio.IPv4.
Registering new address record for fe80::42:53ff:fef6:ad9b on docker0.*.
Registering new address record for 172.17.0.1 on docker0.IPv4.
Registering new address record for fd23:b292:d298:4011:6ccc:c48c:cab:6f51 on enp6s18.*.
Registering new address record for 192.168.1.70 on enp6s18.IPv4.
Registering new address record for ::1 on lo.*.
Registering new address record for 127.0.0.1 on lo.IPv4.
[2022-12-16 02:17:13] [  LOG]     mdns: Avahi state change: Client collision
[2022-12-16 02:17:13] [  LOG]     mdns: Avahi state change: Client registering
2022-12-15 18:17:23,385 INFO  PlayerSession:69 - Created new session. {id: /LPVhtejGfjVFe0o0FgjqQ}
2022-12-15 18:17:24,216 INFO  DeviceStateHandler:276 - Put state. {ts: 1671128243402, connId: MTVhM...3QTk=, reason: PLAYER_STATE_CHANGED}
2022-12-15 18:17:24,686 INFO  DeviceStateHandler:276 - Put state. {ts: 1671128243422, connId: MTVhM...3QTk=, reason: PLAYER_STATE_CHANGED}
2022-12-15 18:17:25,010 INFO  PlayerQueueEntry:125 - Loaded track. {name: 'Burgundy Red', artists: 'Sunset Rollercoaster', duration: 377800, uri: spotify:track:6lgFrbyYUcUBdPyTiRN0RH, id: 01beca013d1f933cfdd480eec0bb1fd7}
2022-12-15 18:17:25,642 INFO  DeviceStateHandler:276 - Put state. {ts: 1671128245114, connId: MTVhM...3QTk=, reason: PLAYER_STATE_CHANGED}
[2022-12-16 02:17:28] [  LOG]     http: Request to file:/tmp/owntone.aMjdfB.jpg failed: Couldn't read a file:// file
[2022-12-16 02:17:28] [  LOG]  artwork: Request to 'file:/tmp/owntone.aMjdfB.jpg' failed with return value -1
[2022-12-16 02:17:28] [  LOG]  artwork: Source 'stream' returned an error for 'librespot-java'
[2022-12-16 02:17:28] [  LOG]     http: Request to file:/tmp/owntone.aMjdfB.jpg failed: Couldn't read a file:// file
[2022-12-16 02:17:28] [  LOG]  artwork: Request to 'file:/tmp/owntone.aMjdfB.jpg' failed with return value -1
[2022-12-16 02:17:28] [  LOG]  artwork: Source 'stream' returned an error for 'librespot-java'
[2022-12-16 02:17:29] [  LOG]  artwork: Request to 'file:/tmp/owntone.HlkdhB.jpg' failed with code 0
[2022-12-16 02:17:29] [  LOG]  artwork: Source 'stream' returned an error for 'librespot-java'
[2022-12-16 02:17:29] [  LOG]  artwork: Request to 'file:/tmp/owntone.HlkdhB.jpg' failed with code 0
[2022-12-16 02:17:29] [  LOG]  artwork: Source 'stream' returned an error for 'librespot-java'
Withdrawing address record for fe80::b4c1:f9ff:fe6f:fa82 on veth030d762.
Withdrawing address record for fe80::b46d:40ff:fe74:4ef4 on veth6c757f5.
Withdrawing address record for fe80::f839:81ff:feea:3d3e on vethcedecb9.
Withdrawing address record for fe80::f052:32ff:fe50:623d on veth000fdb3.
Withdrawing address record for fe80::c4b1:e5ff:fe4c:883f on veth5c9ac3b.
Withdrawing address record for fe80::481:4ff:fe7b:98d1 on vethb49d1d5.
Withdrawing address record for fe80::bca1:feff:fea8:3abf on veth3a40eae.
Withdrawing address record for fe80::88ad:89ff:fef8:36f1 on vethea43337.
Withdrawing address record for fe80::b83a:26ff:feef:465a on veth51c31fb.
Withdrawing address record for fe80::e89b:eff:fe16:9518 on veth0a68914.
Withdrawing address record for fe80::2cc1:b8ff:fed1:aa1e on veth76848d9.
Withdrawing address record for fe80::b0e2:b7ff:fe09:e602 on vethd7bbce6.
Withdrawing address record for fe80::60b6:58ff:fecc:7ffa on veth8e6ba93.
Withdrawing address record for fe80::ac49:9dff:fed6:fcfc on vethd2dd562.
Withdrawing address record for fe80::42:34ff:fe64:4f9e on hassio.
Withdrawing address record for fe80::42:53ff:fef6:ad9b on docker0.
Withdrawing address record for 172.17.0.1 on docker0.
Withdrawing address record for fd23:b292:d298:4011:6ccc:c48c:cab:6f51 on enp6s18.
Withdrawing address record for 192.168.1.70 on enp6s18.
Withdrawing address record for ::1 on lo.
Withdrawing address record for 127.0.0.1 on lo.
Host name conflict, retrying with 63120367-homepod-connect-36
Registering new address record for fe80::b4c1:f9ff:fe6f:fa82 on veth030d762.*.
Registering new address record for fe80::b46d:40ff:fe74:4ef4 on veth6c757f5.*.
Registering new address record for fe80::f839:81ff:feea:3d3e on vethcedecb9.*.
Registering new address record for fe80::f052:32ff:fe50:623d on veth000fdb3.*.
Registering new address record for fe80::c4b1:e5ff:fe4c:883f on veth5c9ac3b.*.
Registering new address record for fe80::481:4ff:fe7b:98d1 on vethb49d1d5.*.
Registering new address record for fe80::bca1:feff:fea8:3abf on veth3a40eae.*.
Registering new address record for fe80::88ad:89ff:fef8:36f1 on vethea43337.*.
Registering new address record for fe80::b83a:26ff:feef:465a on veth51c31fb.*.
[2022-12-16 02:17:33] [  LOG]     mdns: Avahi state change: Client collision
Registering new address record for fe80::e89b:eff:fe16:9518 on veth0a68914.*.
Registering new address record for fe80::2cc1:b8ff:fed1:aa1e on veth76848d9.*.
Registering new address record for fe80::b0e2:b7ff:fe09:e602 on vethd7bbce6.*.
Registering new address record for fe80::60b6:58ff:fecc:7ffa on veth8e6ba93.*.
Registering new address record for fe80::ac49:9dff:fed6:fcfc on vethd2dd562.*.
Registering new address record for fe80::42:34ff:fe64:4f9e on hassio.*.
Registering new address record for 172.30.32.1 on hassio.IPv4.
Registering new address record for fe80::42:53ff:fef6:ad9b on docker0.*.
Registering new address record for 172.17.0.1 on docker0.IPv4.
Registering new address record for fd23:b292:d298:4011:6ccc:c48c:cab:6f51 on enp6s18.*.
Registering new address record for 192.168.1.70 on enp6s18.IPv4.
Registering new address record for ::1 on lo.*.
Registering new address record for 127.0.0.1 on lo.IPv4.
[2022-12-16 02:17:33] [  LOG]     mdns: Avahi state change: Client registering
```

```
	at java.io.RandomAccessFile.seek0(Native Method) ~[?:?]
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:591) ~[?:?]
	at xyz.gianlu.librespot.cache.CacheManager$Handler.writeChunk(CacheManager.java:266) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer.writeChunk(CdnManager.java:271) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:319) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer.access$1500(CdnManager.java:198) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:398) ~[librespot-java.jar:1.6.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2022-12-15 18:20:49,921 ERROR CdnManager:313 - Failed requesting chunk from cache, index: 23
java.io.IOException: Stream Closed
	at java.io.RandomAccessFile.length(Native Method) ~[?:?]
	at xyz.gianlu.librespot.cache.CacheManager$Handler.hasChunk(CacheManager.java:215) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:308) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer.access$1500(CdnManager.java:198) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:398) ~[librespot-java.jar:1.6.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2022-12-15 18:20:49,942 WARN  CdnManager:273 - Failed writing to cache! {index: 23}
java.io.IOException: Stream Closed
	at java.io.RandomAccessFile.seek0(Native Method) ~[?:?]
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:591) ~[?:?]
	at xyz.gianlu.librespot.cache.CacheManager$Handler.writeChunk(CacheManager.java:266) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer.writeChunk(CdnManager.java:271) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:319) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer.access$1500(CdnManager.java:198) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:398) ~[librespot-java.jar:1.6.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2022-12-15 18:20:53,451 ERROR CdnManager:313 - Failed requesting chunk from cache, index: 24
java.io.IOException: Stream Closed
	at java.io.RandomAccessFile.length(Native Method) ~[?:?]
	at xyz.gianlu.librespot.cache.CacheManager$Handler.hasChunk(CacheManager.java:215) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:308) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer.access$1500(CdnManager.java:198) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:398) ~[librespot-java.jar:1.6.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2022-12-15 18:20:53,470 WARN  CdnManager:273 - Failed writing to cache! {index: 24}
java.io.IOException: Stream Closed
	at java.io.RandomAccessFile.seek0(Native Method) ~[?:?]
	at java.io.RandomAccessFile.seek(RandomAccessFile.java:591) ~[?:?]
	at xyz.gianlu.librespot.cache.CacheManager$Handler.writeChunk(CacheManager.java:266) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer.writeChunk(CdnManager.java:271) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:319) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer.access$1500(CdnManager.java:198) ~[librespot-java.jar:1.6.2]
	at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:398) ~[librespot-java.jar:1.6.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```
**Version/Commit**
28.5-ls96

**Comment by scout1256** [comment]
Ummmm......
I got it working...
entity_id: media_player.owntone_output_fang_jian didn't show up before, after turning it on sound appears.

How can I make "media_player.owntone_output_fang_jian" the default player?

**Comment by AlexanderBabel** [comment]
As long as you don't restart owntone it should stay selected. If you do so, you have to select it again.
